apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-svc
  template:
    metadata:
      labels:
        app: ldap-svc
    spec:
      containers:
      - name: ldap-svc
        image: ubuntu:ldap
        command: ["/bin/sh", "-c"]
        args: ["set -xe; service nscd restart; service ssh restart; su sthost01;sleep 2147483647"]
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-svc
  labels:
    app: ldap-svc
spec:
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: ldap-svc
  type: NodePort